### PR TITLE
Egress rules deletion fix

### LINKED ISSUE #966: Iptables rules are persisting after service deletion
**Describe the bug**

When egress rules are deleted some rules persist in nftables/iptables.

**To Reproduce**

**Expected behavior**
Egress Rules should be cleaned if leader changes or pod is dismantled.

**Screenshots**
```
-A KUBE-VIP-EGRESS -d 10.0.0.0/16 -m comment --comment "a3ViZS12aXAK=kube-vip-e2e-test" -j RETURN
-A KUBE-VIP-EGRESS -d 10.96.0.0/12 -m comment --comment "a3ViZS12aXAK=kube-vip-e2e-test" -j RETURN
-A KUBE-VIP-EGRESS -s 172.30.3.22/32 -m comment --comment "a3ViZS12aXAK=kube-vip-e2e-test" -j MARK --set-xmark 0x40/0x40
```

first node with leader
```
time="2024-10-10T15:47:47Z" level=debug msg="[endpoints] processing endpoint [172.30.0.125]"
time="2024-10-10T15:47:47Z" level=debug msg="[endpoints] found local endpoint - address: 172.30.0.125, hostname: , node: cbnutsch-1-default-n22jh-5dqbs"
time="2024-10-10T15:47:47Z" level=debug msg="[endpoints watcher] service e2e-test/hpeocsnf: local endpoint(s) [1], known good [172.30.0.125], active election [false]"
time="2024-10-10T15:47:47Z" level=info msg="(svc election) service [hpeocsnf], namespace [e2e-test], lock name [kubevip-hpeocsnf], host id [cbnutsch-1-default-n22jh-5dqbs]"
I1010 15:47:47.429167       1 leaderelection.go:250] attempting to acquire leader lease e2e-test/kubevip-hpeocsnf...
time="2024-10-10T15:47:47Z" level=info msg="(svc election) new leader elected: cbnutsch-1-default-n22jh-65p2h"
I1010 15:47:49.394077       1 leaderelection.go:260] successfully acquired lease e2e-test/kubevip-hpeocsnf
time="2024-10-10T15:47:49Z" level=debug msg="[STARTING] Service Sync"
time="2024-10-10T15:47:49Z" level=debug msg="init enable service security: false"
time="2024-10-10T15:47:49Z" level=info msg="(svcs) adding VIP [10.100.76.132] via lo for [e2e-test/hpeocsnf]"
time="2024-10-10T15:47:49Z" level=debug msg="(svcs) will update [e2e-test/hpeocsnf]"
time="2024-10-10T15:47:49Z" level=debug msg="Flushing conntrack rules for service [hpeocsnf]"
time="2024-10-10T15:47:49Z" level=debug msg="Enabling egress for the service [hpeocsnf]"
time="2024-10-10T15:47:49Z" level=warning msg="pods is forbidden: User \"system:serviceaccount:e2e-test:kube-vip-serviceaccount\" cannot list resource \"pods\" in API group \"\" in the namespace \"kube-system\""
time="2024-10-10T15:47:49Z" level=info msg="[Egress] pod CIDR [10.0.0.0/16], service CIDR [10.96.0.0/12] for vip [10.100.76.132] / pod [172.30.0.125]"
time="2024-10-10T15:47:49Z" level=info msg="[egress] Creating an iptables client, nftables mode [false]"
time="2024-10-10T15:47:49Z" level=info msg="[egress] Checking for Chain [KUBE-VIP-EGRESS]"
time="2024-10-10T15:47:49Z" level=info msg="[egress] Adding jump for subnet [10.0.0.0/16] to RETURN to previous chain/rules"
time="2024-10-10T15:47:49Z" level=info msg="[egress] Adding jump for subnet [10.96.0.0/12] to RETURN to previous chain/rules"
time="2024-10-10T15:47:49Z" level=info msg="[egress] Marking packets on network [172.30.0.125/32]"
time="2024-10-10T15:47:49Z" level=info msg="[egress] Adding jump from mangle prerouting to [KUBE-VIP-EGRESS]"
time="2024-10-10T15:47:49Z" level=info msg="[egress] Adding source nat from [172.30.0.125] => [10.100.76.132]"
time="2024-10-10T15:47:49Z" level=info msg="[service] synchronised in 172ms"
time="2024-10-10T15:47:54Z" level=debug msg="[endpoints] processing endpoint [172.30.0.125]"
```

second node with standby.
```
time="2024-10-10T15:47:49Z" level=debug msg="[STARTING] Service Sync"
time="2024-10-10T15:47:49Z" level=debug msg="init enable service security: false"
time="2024-10-10T15:47:49Z" level=info msg="(svcs) adding VIP [10.100.76.132] via lo for [e2e-test/hpeocsnf]"
time="2024-10-10T15:47:49Z" level=debug msg="(svcs) will update [e2e-test/hpeocsnf]"
time="2024-10-10T15:47:49Z" level=debug msg="Flushing conntrack rules for service [hpeocsnf]"
time="2024-10-10T15:47:49Z" level=debug msg="Enabling egress for the service [hpeocsnf]"
time="2024-10-10T15:47:49Z" level=warning msg="pods is forbidden: User \"system:serviceaccount:e2e-test:kube-vip-serviceaccount\" cannot list resource \"pods\" in API group \"\" in the namespace \"kube-system\""
time="2024-10-10T15:47:49Z" level=info msg="[Egress] pod CIDR [10.0.0.0/16], service CIDR [10.96.0.0/12] for vip [10.100.76.132] / pod [172.30.0.125]"
time="2024-10-10T15:47:49Z" level=info msg="[egress] Creating an iptables client, nftables mode [false]"
time="2024-10-10T15:47:49Z" level=info msg="[egress] Checking for Chain [KUBE-VIP-EGRESS]"
time="2024-10-10T15:47:49Z" level=info msg="[egress] Adding jump for subnet [10.0.0.0/16] to RETURN to previous chain/rules"
time="2024-10-10T15:47:49Z" level=info msg="[egress] Adding jump for subnet [10.96.0.0/12] to RETURN to previous chain/rules"
time="2024-10-10T15:47:49Z" level=info msg="[egress] Marking packets on network [172.30.0.125/32]"
time="2024-10-10T15:47:49Z" level=info msg="[egress] Adding jump from mangle prerouting to [KUBE-VIP-EGRESS]"
time="2024-10-10T15:47:49Z" level=info msg="[egress] Adding source nat from [172.30.0.125] => [10.100.76.132]"
time="2024-10-10T15:47:49Z" level=info msg="[service] synchronised in 172ms"
time="2024-10-10T15:47:54Z" level=debug msg="[endpoints] processing endpoint [172.30.0.125]"
time="2024-10-10T15:47:54Z" level=debug msg="[endpoints] found local endpoint - address: 172.30.0.125, hostname: , node: cbnutsch-1-default-n22jh-5dqbs"
time="2024-10-10T15:47:54Z" level=debug msg="[endpoints watcher] service e2e-test/hpeocsnf: local endpoint(s) [1], known good [172.30.0.125], active election [true]"
time="2024-10-10T15:47:54Z" level=info msg="(svcs) [nginx-plus-wsg-nginx-ingress-controller] specified no loadBalancer class, expected [kubeviplb], ignoring"
time="2024-10-10T15:47:59Z" level=debug msg="[endpoints] processing endpoint [172.30.3.22]"
time="2024-10-10T15:47:59Z" level=warning msg="[endpoints] existing [172.30.0.125] has been removed, no remaining endpoints for leaderElection"
time="2024-10-10T15:47:59Z" level=debug msg="[endpoints watcher] service e2e-test/hpeocsnf: local endpoint(s) [0], known good [], active election [false]"
time="2024-10-10T15:47:59Z" level=info msg="(svc election) service [hpeocsnf] leader lost: [cbnutsch-1-default-n22jh-5dqbs]"
time="2024-10-10T15:47:59Z" level=debug msg="Looking for [5002134b-4e1f-4f01-8083-eb70026df473], found [5002134b-4e1f-4f01-8083-eb70026df473]"
time="2024-10-10T15:47:59Z" level=info msg="[LOADBALANCER] Stopping load balancers"
time="2024-10-10T15:47:59Z" level=info msg="[VIP] Deleting Route for Virtual IP [10.100.76.132]"
time="2024-10-10T15:47:59Z" level=info msg="service [hpeocsnf] has an egress re-write enabled"
time="2024-10-10T15:47:59Z" level=info msg="[egress] Creating an iptables client, nftables mode [false]"
time="2024-10-10T15:47:59Z" level=info msg="[egress] Stopping marking packets on network [172.30.0.125]"
time="2024-10-10T15:47:59Z" level=info msg="[egress] Removing source nat from [172.30.0.125] => [10.100.76.132]"
time="2024-10-10T15:47:59Z" level=info msg="Removed [5002134b-4e1f-4f01-8083-eb70026df473] from manager, [0] advertised services remain"
time="2024-10-10T15:47:59Z" level=info msg="(svc election) for service [hpeocsnf] stopping"
time="2024-10-10T15:48:01Z" level=debug msg="(svcs) [hpeocsnf] has been added/modified with addresses [[10.100.76.132]]"
```
**Environment (please complete the following information):**
 - OS/Distro: Ubuntu 20.04
 - Kubernetes Version: 1.29.x
 - Kube-vip Version: 0.8.4

**`Kube-vip.yaml`:**
```yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kube-vip-role
  namespace: test
rules:
- apiGroups:
  - ""
  resources:
  - services
  - services/status
  - nodes
  - endpoints
  verbs:
  - list
  - get
  - watch
  - update
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - list
  - get
  - watch
  - update
  - create
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-vip-serviceaccount
  namespace: test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kube-vip-rolebinding
  namespace: test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kube-vip-role
subjects:
- kind: ServiceAccount
  name: kube-vip-serviceaccount
  namespace: test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  name: kube-vip
  namespace: test
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-vip
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: kube-vip
        app.kubernetes.io/version: v0.8.4
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: Exists
            weight: 1
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: test
                operator: In
                values:
                - "true"
            namespaceSelector: {}
            topologyKey: kubernetes.io/hostname
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - kube-vip
            topologyKey: kubernetes.io/hostname
      containers:
      - args:
        - manager
        - --prometheusHTTPServer
        - ""
        env:
        - name: svc_namespace
          value: test
        - name: lb_class_legacy_handling
          value: "false"
        - name: lb_class_name
          value: kubeviplb
        - name: vip_routingtableid
          value: "2864285557"
        - name: vip_routingtable
          value: "true"
        - name: vip_cleanroutingtable
          value: "true"
        - name: svc_election
          value: "true"
        - name: vip_interface
          value: lo
        - name: vip_cidr
          value: "32"
        - name: vip_arp
          value: "false"
        - name: port
          value: "6443"
        - name: svc_enable
          value: "true"
        - name: vip_startleader
          value: "true"
        - name: vip_addpeerstolb
          value: "true"
        - name: vip_leaseduration
          value: "3"
        - name: vip_renewdeadline
          value: "2"
        - name: vip_retryperiod
          value: "1"
        - name: egress_podcidr
          value: 172.30.0.0/18
        - name: egress_servicecidr
          value: 172.30.64.0/18
        - name: vip_loglevel
          value: "5"
        - name: egress_withnftables
          value: "true"
        - name: EGRESS_CLEAN
          value: "true"
        - name: dnsMode
          value: ipv4
        image: artifactory.devops.telekom.de/dtt-cb-cbnutsch-dev-docker/kube-vip-iptables:v0.8.4
        imagePullPolicy: IfNotPresent
        name: kube-vip
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 500m
            memory: 256Mi
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            - SYS_TIME
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: kube-vip-serviceaccount
      serviceAccountName: kube-vip-serviceaccount
      terminationGracePeriodSeconds: 30
```
**Additional context**

This could be somehow related to egress IPv6 and the auto detect of the pod/service code ranges.

### PR DESCRIPTION
**Pull request by p-strusiewiczsurmacki-mobica**
This PR fixes #966 

It introduces a few changes:

1. Egress rules should be now deleted properly in service-election routing table mode when service is deleted, election is lost or kube-vip's pod is terminated.

2. Auto service/pod CIDR discovery will now not be used if `egress_servicecidr` and/or `egress_podcidr` is defined.

3. A minor change in the e2e tests - docker image will be now loaded only after the cluster was created. (this can be discarded in favor of better e2e test fix if possible. Added that just to run the tests for now.)

### CODE REVIEW

**Comment by Cellebyte** [comment]
@p-strusiewiczsurmacki-mobica @thebsdbox I will test it hopefully today in the corresponding use-case with the customer.
Fingers crossed that it works now as expected.

**Comment by thebsdbox** [comment]
Sounds good, I'm at a conference today. But I can cut a new release later on.

**Comment by Cellebyte** [comment]
@p-strusiewiczsurmacki-mobica we will start another trial on Monday with the customer.

**Comment by thebsdbox** [comment]
OK cool, please let me know when there is some feedback :-)

File: pkg/manager/manager_table.go [hunk 1]
```diff
@@ -36,6 +39,19 @@ func (sm *Manager) startTableMode(id string) error {
 		}()
 	}
 
+	egressCleanEnv := os.Getenv("EGRESS_CLEAN")
```
Comment (thebsdbox) [inline pkg/manager/manager_table.go:42]: This is now `vip.ClearIPTables(sm.config.EgressWithNftables, sm.config.ServiceNamespace, iptables.ProtocolIPv4)` in places like `manager_arp.go`, should this be replaced here too?

File: pkg/manager/service_egress.go [hunk 2]
```diff
@@ -194,24 +240,19 @@ func (sm *Manager) configureEgress(vipIP, podIP, destinationPorts, namespace str
 }
 
 func (sm *Manager) AutoDiscoverCIDRs() (serviceCIDR, podCIDR string, err error) {
-	podList, err := sm.clientSet.CoreV1().Pods("kube-system").List(context.TODO(), v1.ListOptions{})
-	if err != nil {
-		return "", "", err
+	log.Debugf("Trying to automatically discover Service and Pod CIDRs")
+	options := v1.ListOptions{
```
Comment (thebsdbox) [inline pkg/manager/service_egress.go:244]: Nice, much clearer than grabbing all pods :-)

File: pkg/vip/egress.go [hunk 3]
```diff
@@ -376,3 +376,17 @@ func (e *Egress) findExistingVIP(rules []string, vip string) [][]string {
 
 	return foundRules
 }
+
+func ClearIPTables(useNftables bool, namespace string, protocol iptables.Protocol) {
+	i, err := CreateIptablesClient(useNftables, namespace, protocol)
+	if err != nil {
+		log.Warnf("(egress) Unable to clean any dangling egress rules [%v]", err)
```
Comment (thebsdbox) [inline pkg/vip/egress.go:383]: Randomly the formatting is wrong here as the log format is square brackets around the functionality  ¯\_(ツ)_/¯ (probably my mistake from earlier)

**Review by thebsdbox — APPROVED** [review]
There are a few little things that I raised, but I don't consider anything blocking. Everything raised is purely cosmetic.

File: pkg/manager/manager_table.go (hunk 1 above)
Comment (p-strusiewiczsurmacki-mobica) [reply pkg/manager/manager_table.go:42]: I don't quite understand. :smile:  `vip.ClearIPTables` function is used here as well as in other places I believe.

File: pkg/vip/egress.go (hunk 3 above)
Comment (p-strusiewiczsurmacki-mobica) [reply pkg/vip/egress.go]: Fixed that. :)

**Comment by thebsdbox** [comment]
How close are we to getting this merged?

**Comment by Cellebyte** [comment]
@thebsdbox we are just troubleshooting why iptables rules do not get persisted on the nodes.

**Comment by p-strusiewiczsurmacki-mobica** [comment]
It seems that the rules were there, but @Cellebyte was not able to see them due to node's configuration. PR is now open.
