### PR TITLE
Fixed DDNS nil pointer dereference (1305)

### LINKED ISSUE #1305: Panic during leader election
**Describe the bug**
New cluster with 4 nodes, after installing kube-vip as a DaemonSet, the pods keep crashing right after startup with a nil pointer dereference.

````
2025/10/22 06:15:24 INFO kube-vip.io version=v1.0.1 build=8409073e7ac0087b475a137aed3434066d5629e4
2025/10/22 06:15:24 INFO starting namespace=kube-system Mode=ARP "Control Plane"=true Services=false
2025/10/22 06:15:24 INFO prometheus HTTP server started
2025/10/22 06:15:24 INFO using node name name=r08-pool1-nhpdp-kwfk8
2025/10/22 06:15:24 INFO Starting Kube-vip Manager with the ARP engine
2025/10/22 06:15:24 INFO Start ARP/NDP advertisement
2025/10/22 06:15:24 INFO Starting UPNP Port Refresher
2025/10/22 06:15:24 INFO [ARP manager] starting ARP/NDP advertisement
2025/10/22 06:15:24 INFO cluster membership namespace=kube-system lock=plndr-cp-lock id=r08-pool1-nhpdp-kwfk8
I1022 06:15:24.375109       1 leaderelection.go:257] attempting to acquire leader lease kube-system/plndr-cp-lock...
2025/10/22 06:15:24 INFO New leader leader=r08-pool1-nhpdp-t7vsf
I1022 06:15:29.675234       1 leaderelection.go:271] successfully acquired lease kube-system/plndr-cp-lock
2025/10/22 06:15:29 INFO New leader leader=r08-pool1-nhpdp-kwfk8
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x17b2f51]
goroutine 39 [running]:
github.com/kube-vip/kube-vip/pkg/vip.(*network).IP(0xc000107918?)
	/src/pkg/vip/address.go:681 +0x71
github.com/kube-vip/kube-vip/pkg/vip.(*network).SetMask(0xc0000f01e0, {0xc00001004b, 0x2})
	/src/pkg/vip/address.go:761 +0x4c
github.com/kube-vip/kube-vip/pkg/cluster.(*Cluster).vipService(0xc000416580, {0x29aece0, 0xc000240370}, {0x29aece0, 0xc0002403c0}, 0x3eb7f00, 0xc0003c61a0, 0x0, 0xc00005c810)
	/src/pkg/cluster/service.go:49 +0x1d0
github.com/kube-vip/kube-vip/pkg/cluster.(*Cluster).StartCluster.func3({0x0?, 0x0?})
	/src/pkg/cluster/clusterLeaderElection.go:169 +0x3f
created by k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run in goroutine 12
	/go/pkg/mod/k8s.io/client-go@v0.34.1/tools/leaderelection/leaderelection.go:220 +0xe6
````

**To Reproduce**
1. Create yaml file:
  ````
podman run --network=host --rm ghcr.io/kube-vip/kube-vip:v1.0.1 manifest daemonset \
    --arp \
    --inCluster \
    --taint \
    --controlplane \
    --interface ens160 \
    --ddns \
    --address r08-control.some.zone \
    | tee kube-vip.yaml
````
2. `kubectl apply -f kube-vip.yaml`
3. Watch the pods crash with the above mentioned error.

**Expected behavior**
Should work without problems. Like it did in the past. Problem occurs with 1.0.1 and 1.0.0. Did not test older versions.

**Environment (please complete the following information):**
 - OS/Distro: Ubuntu 22.04
 - Kubernetes Version: 1.31.12
 - Kube-vip Version: 1.0.1

**`Kube-vip.yaml`:**

````
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/name: kube-vip-ds
    app.kubernetes.io/version: v1.0.1
  name: kube-vip-ds
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-vip-ds
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kube-vip-ds
        app.kubernetes.io/version: v1.0.1
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
      containers:
      - args:
        - manager
        env:
        - name: vip_arp
          value: "true"
        - name: port
          value: "6443"
        - name: vip_nodename
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: vip_interface
          value: ens160
        - name: vip_subnet
          value: "32"
        - name: dns_mode
          value: first
        - name: cp_enable
          value: "true"
        - name: cp_namespace
          value: kube-system
        - name: vip_ddns
          value: "true"
        - name: address
          value: r08-control.some.zone
        - name: prometheus_server
          value: :2112
        image: ghcr.io/kube-vip/kube-vip:v1.0.1
        imagePullPolicy: IfNotPresent
        name: kube-vip
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            drop:
            - ALL
      hostNetwork: true
      serviceAccountName: kube-vip
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
  updateStrategy: {}
````

**Additional context**

### PR DESCRIPTION
**Pull request by p-strusiewiczsurmacki-mobica**
This PR should fix #1305 

It turned out that when DDNS was being used, the `configurator.address` was nil and therefore raising nil pointer dereference panic.

Additionally, fixed some minor issues I have found when trying to debug this issue.

### CODE REVIEW

**Comment by p-strusiewiczsurmacki-mobica** [comment]
It seems this fixes #1305 according to the comment in the issue :)

File: pkg/vip/address.go [hunk 1]
```diff
@@ -771,13 +806,16 @@ func (configurator *network) SetMask(mask string) error {
 	size := 32
 	family := "IPv4"
 
-	if utils.IsIPv6(configurator.IP()) {
-		size = 128
-		family = "IPv6"
-	}
+	if configurator.IP() != "" {
+		if utils.IsIPv6(configurator.IP()) {
+			size = 128
```
Comment (Cellebyte) [inline pkg/vip/address.go]: Can we use the constants here? :)

File: pkg/vip/util.go [hunk 2]
```diff
@@ -142,3 +143,22 @@ func GetNonLinkLocalIP(iface *netlink.Link, family int) (string, error) {
...
 	return "", fmt.Errorf("failed to find non-local IP on interface: %s", (*iface).Attrs().Name)
 }
+
+func selectSubnet(address string, subnets []string) string {
+	subnet := ""
+	if utils.IsIPv4(address) {
+		if subnets[0] != "" {
+			subnet = subnets[0]
+		} else {
+			subnet = "32"
```
Comment (Cellebyte) [inline pkg/vip/util.go]: Same here

File: pkg/vip/address.go (hunk 1 above)
Comment (p-strusiewiczsurmacki-mobica) [reply pkg/vip/address.go]: Done :)

File: pkg/vip/util.go (hunk 2 above)
Comment (p-strusiewiczsurmacki-mobica) [reply pkg/vip/util.go]: Done :)
